stages:
  preprocess:
    cmd: python3 preprocess.py
    deps:
    - data/raw/creditcard.csv
    - preprocess.py
    outs:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
  train:
    cmd: python3 train.py
    deps:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
    - train.py
    outs:
    - models/fraud_model.pkl
